# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-29 15:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_auto_20170329_0958'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.AddField(
            model_name='job',
            name='collection_point',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='destination_point',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
